#to get the key
#Go to https://openrouter.ai/
#singup 
#and go to the keys
#Create a key 
#Copy and paste on main.py
#this is how the key look like 
OPENROUTER_API_KEY = "sk-or-v1-006580c2fa723570ef42bfae656e106847fb73268f419ff0f6796aea"
